version: '3.7'
services:
    postgres:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: cht-postgres
        environment:
            POSTGRES_DB: cht
            POSTGRES_USER: cht
            POSTGRES_PASSWORD: cht_password
            COUCH2PG_USER: cht_couch2pg
            COUCH2PG_USER_PASSWORD: couch2pg_password
            DB_OWNER_GROUP: cht_analytics
        volumes:
            - cht-postgres-data:/var/lib/postgresql/data

volumes:
    cht-postgres-data:
        name: cht-postgres-data
