#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" --variable=POSTGRES_DB="$POSTGRES_DB" --variable=DB_OWNER_GROUP="$DB_OWNER_GROUP" --variable=COUCH2PG_USER="$COUCH2PG_USER" --variable=COUCH2PG_USER_PASSWORD="$COUCH2PG_USER_PASSWORD"<<-EOSQL
    CREATE ROLE :DB_OWNER_GROUP;
    CREATE USER :COUCH2PG_USER  WITH PASSWORD :'COUCH2PG_USER_PASSWORD';
    GRANT ALL PRIVILEGES ON DATABASE :POSTGRES_DB TO :DB_OWNER_GROUP;
    GRANT :DB_OWNER_GROUP TO :COUCH2PG_USER;
EOSQL
